name: Infection Risk Prediction

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-predictor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install correct Colab versions
        run: |
          pip install --upgrade pip
          pip install numpy==1.26.4
          pip install scipy==1.11.4
          pip install scikit-learn==1.4.2
          pip install joblib==1.3.2
          pip install pandas
          pip install requests

      - name: Run script
        env:
          READ_CHANNEL_ID: ${{ secrets.READ_CHANNEL_ID }}
          READ_API_KEY: ${{ secrets.READ_API_KEY }}
          PREDICTION_WRITE_API_KEY: ${{ secrets.PREDICTION_WRITE_API_KEY }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: python infection_risk_alert.py
